<template>
    <div>
        <NitroHeader></NitroHeader>
        <NitroContent></NitroContent>
        <NitroPrivilege></NitroPrivilege>
        <NitroPlan></NitroPlan>
        <NitroFaq></NitroFaq>
    </div>
</template>